development:
  # adapter: redis
  adapter: postgresql
  url: <%= ENV.fetch("DATABASE_URL") { "postgres://localhost:5432/licon_development" } %>
  channel_prefix: licon_production

test:
  adapter: test

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  channel_prefix: licon_production
