development:
  adapter: redis
  # adapter: async
  url: <%= ENV.fetch("REDIS_URL") { "redis://redis/1" } %>
  channel_prefix: licon_production

test:
  adapter: test

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: licon_production
